- name: aws_setups
  hosts: local
  connection: local
  vars:
    image: ami-0220d79f3f480ecf5
    instances: ["mysql","mq"]
    act: create
  tasks:
    - name: instance creation
      amazon.aws.ec2_instance:
        name: "roboshop-{{item}}"
        region: us-east-1
        instance_type: t3.micro
        state: present
        image_id: "{{image}}"
        security_group:
          - "roboshop-{{item}}"
      loop: "{{instances}}"
      register: output
      when: act == "create"

    - name: print the out put
      debug:
        msg: "{{output}}"
