- name: aws_setup
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    instances: ["mysql","mq","frontend"]
    act: create
    domain_name: sudhakar.shop
  tasks:
    - name: crate instance
      amazon.aws.ec2_instance:
        name: "roboshop-{{ item }}"
        instance_type: t3.micro
        image_id: "{{ami_id}}"
        security_groups:
          - "roboshop-{{ item }}"
        state: present
      loop: "{{ instances }}"
      register: ec2_output
      when: act == "create"


    - name: create route53
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: act == "create"


    - name: for route53 frontend
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A 
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_output.results }}"
      when:
        - item.item == "frontend"
        - act == "create"


    - name: delete r53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}.{{ domain_name }}" 
        ttl: 1
        type: A
      loop: "{{ instances  }}"  
      when: act == "delete"

    - name: delete r53 record for frontend
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}" # daws90s.shop
        ttl: 1
        type: A
      loop: "{{ instances  }}"  
      when: 
        - action == "delete"
        - item == "frontend"
  
    - name: delete ec2 instances
      amazon.aws.ec2_instance:
        state: absent
        name: "roboshop-{{ item }}"
        wait: false
      loop: "{{ instances  }}"  
      when: act == "delete"
        



